# Generated by Django 3.0.8 on 2020-08-10 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='дата задания')),
                ('done', models.BooleanField(default=False, verbose_name='выполнено')),
            ],
            options={
                'verbose_name': 'Задача на сбор статей',
                'verbose_name_plural': 'Задачи на сбор статей',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=256, verbose_name='Заголовок статьи')),
                ('url', models.URLField(verbose_name='url статьи')),
                ('text', models.CharField(default='', max_length=701, verbose_name='700 символов текста статьи')),
                ('id_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='api.Task')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
